import { defineStore } from "pinia";
import { reactive } from "vue";
import type { StoreInfo } from "../includes/interfaces";

export const useStoreInfo = defineStore(
    "storeInfo",
    () => {
        let storeInfo = reactive<StoreInfo>({
            event: {
                id: 2,
                event_ref: "fd3da7180a",
                event_name: "gtoc food fest",
                start_date: "2025-09-09",
                end_date: "2025-09-25",
                participant_fee: 2500,
                qr_code:
                    "https://fra1.digitaloceanspaces.com/leyyow-crm/static/images/events/qr_code/gtoc_food_fest_qr.png?AWSAccessKeyId=DO006CA8UQDTG3VKR3V9&Signature=mpNZ8OVJjsMm5Y6qk3VhErrl7jw%3D&Expires=1745528995",
                created: "2025-04-24T13:43:45.304447+01:00",
                store: {
                    id: 3,
                    store_name: "leyyow",
                    logo: "https://fra1.digitaloceanspaces.com/leyyow-crm/static/images/7.jpg?AWSAccessKeyId=DO00BNRYB73MUAMAH7V2&Signature=EeKGAKN7%2F24jzB8KnEV7mb%2BIDuY%3D&Expires=1745553193",
                    opening_time: "08:00:00",
                    website: "",
                    instagram: "",
                    twitter: "",
                    facebook: "",
                    currency: "NGN",
                    phone_number: "08012345678",
                },
            },
            products: [
                {
                    id: 765,
                    product_name: "avatar 2",
                    product_type: "",
                    description: "",
                    price: 20000,
                    total_stock: 20,
                    has_variant: false,
                    display: true,
                    discount: "",
                    discount_type: "0",
                    has_discount: false,
                    slug: "demo",
                    store: "Demo",
                    temp_id: "",
                    category: null,
                    rating: "0.0",
                    review_count: 0,
                    rate_tracking: "0,0,0,0,0",
                    strict_stock_count: true,
                    created: "2025-04-17T14:59:55.074364+01:00",
                    last_sale: "2025-04-22T23:52:51.675483+01:00",
                    owner: null,
                    options1: "",
                    options2: "",
                    options3: "",
                    variants: "",
                    combinations: null,
                    images: [
                        {
                            id: 546,
                            type: "1",
                            image: "https://fra1.digitaloceanspaces.com/leyyow-crm/static/images/avatar.webp?AWSAccessKeyId=DO00BNRYB73MUAMAH7V2&Signature=0YZZ548cXPmpLE%2BYVtkVErMwfNE%3D&Expires=1745552725",
                            name: "765_546_lg_avat",
                            store: "Demo",
                            product: 765,
                        },
                    ],
                    sku: [
                        {
                            id: 486,
                            sku: "d0246e8d-9111-43d4-ba7e-28ea037f430b",
                            option1: "",
                            option2: "",
                            option3: "",
                            has_discount: false,
                            sku_discount: "",
                            sku_discount_type: "0",
                            price: 20000,
                            qty: 19,
                            events_qty: {
                                2: 3,
                            },
                        },
                    ],
                    events: [],
                },
                {
                    id: 661,
                    product_name: "Two variants",
                    product_type: "",
                    description: "",
                    price: 5000,
                    total_stock: 60,
                    has_variant: true,
                    display: true,
                    discount: "",
                    discount_type: "0",
                    has_discount: false,
                    slug: "demo",
                    store: "Demo",
                    temp_id: "",
                    category: null,
                    rating: "0.0",
                    review_count: 0,
                    rate_tracking: "0,0,0,0,0",
                    strict_stock_count: true,
                    created: "2025-04-11T11:17:51.591243+01:00",
                    last_sale: "2025-04-17T19:43:59.800863+01:00",
                    owner: null,
                    options1: "Small,Medium",
                    options2: "Blue,Green",
                    options3: "",
                    variants: "Size,Colour",
                    combinations: null,
                    images: [
                        {
                            id: 494,
                            type: "1",
                            image: "https://fra1.digitaloceanspaces.com/leyyow-crm/static/images/2.png?AWSAccessKeyId=DO00BNRYB73MUAMAH7V2&Signature=n8twGQkEXREYcZsXKeezvcyfcxQ%3D&Expires=1745552725",
                            name: "661_494_lg_Two ",
                            store: "Demo",
                            product: 661,
                        },
                    ],
                    sku: [
                        {
                            id: 105,
                            sku: "4f080c0d-a527-4081-bf0c-804db150f4c0",
                            option1: "Small",
                            option2: "Blue",
                            option3: "",
                            has_discount: false,
                            sku_discount: "",
                            sku_discount_type: "0",
                            price: 5000,
                            qty: 15,
                            events_qty: {
                                2: 3,
                            },
                        },
                        {
                            id: 108,
                            sku: "767b72fc-ddab-4325-a889-aaef1552a5f5",
                            option1: "Medium",
                            option2: "Green",
                            option3: "",
                            has_discount: false,
                            sku_discount: "",
                            sku_discount_type: "0",
                            price: 5000,
                            qty: 15,
                            events_qty: null,
                        },
                        {
                            id: 107,
                            sku: "db7678ab-2664-482a-b38d-a5189fc0211f",
                            option1: "Medium",
                            option2: "Blue",
                            option3: "",
                            has_discount: false,
                            sku_discount: "",
                            sku_discount_type: "0",
                            price: 5000,
                            qty: 15,
                            events_qty: null,
                        },
                        {
                            id: 106,
                            sku: "420fdc09-f5fa-44e4-a858-e45beed3249f",
                            option1: "Small",
                            option2: "Green",
                            option3: "",
                            has_discount: false,
                            sku_discount: "",
                            sku_discount_type: "0",
                            price: 5000,
                            qty: 13,
                            events_qty: {
                                2: 10,
                            },
                        },
                    ],
                    events: [],
                },
                {
                    id: 751,
                    product_name: "avatar",
                    product_type: "",
                    description: "this is an avatar NFT.",
                    price: 7000,
                    total_stock: 3,
                    has_variant: true,
                    display: true,
                    discount: "",
                    discount_type: "0",
                    has_discount: false,
                    slug: "demo",
                    store: "Demo",
                    temp_id: "",
                    category: null,
                    rating: "0.0",
                    review_count: 0,
                    rate_tracking: "0,0,0,0,0",
                    strict_stock_count: true,
                    created: "2025-04-17T01:35:09.183094+01:00",
                    last_sale: "2025-04-22T23:52:51.680754+01:00",
                    owner: null,
                    options1: "black,white",
                    options2: "",
                    options3: "",
                    variants: "color",
                    combinations: null,
                    images: [
                        {
                            id: 534,
                            type: "1",
                            image: "https://fra1.digitaloceanspaces.com/leyyow-crm/static/images/avatar.webp?AWSAccessKeyId=DO00BNRYB73MUAMAH7V2&Signature=0YZZ548cXPmpLE%2BYVtkVErMwfNE%3D&Expires=1745552725",
                            name: "751_534_lg_avat",
                            store: "Demo",
                            product: 751,
                        },
                        {
                            id: 544,
                            type: "1",
                            image: "https://fra1.digitaloceanspaces.com/leyyow-crm/static/images/image-1.jpg?AWSAccessKeyId=DO00BNRYB73MUAMAH7V2&Signature=HkGye3yIc4VaqwGicN%2FOhoAvjt4%3D&Expires=1745552725",
                            name: "751_544_lg_avat",
                            store: "Demo",
                            product: 751,
                        },
                        {
                            id: 545,
                            type: "1",
                            image: "https://fra1.digitaloceanspaces.com/leyyow-crm/static/images/image-3.jpg?AWSAccessKeyId=DO00BNRYB73MUAMAH7V2&Signature=AWcuB1%2BnGKr1dBv9X6eG8u471kU%3D&Expires=1745552725",
                            name: "751_545_lg_avat",
                            store: "Demo",
                            product: 751,
                        },
                    ],
                    sku: [
                        {
                            id: 485,
                            sku: "d09eadf9-5272-402a-8c23-879bd01a1b9e",
                            option1: "white",
                            option2: "",
                            option3: "",
                            has_discount: false,
                            sku_discount: "",
                            sku_discount_type: "0",
                            price: 7000,
                            qty: 2,
                            events_qty: {
                                2: 2
                            },
                        },
                        {
                            id: 484,
                            sku: "17dde8a5-cb7b-4510-a554-f9749ae7f3a1",
                            option1: "black",
                            option2: "",
                            option3: "",
                            has_discount: false,
                            sku_discount: "",
                            sku_discount_type: "0",
                            price: 5000,
                            qty: 0,
                            events_qty: null,
                        },
                    ],
                    events: [],
                },
            ],
        });

        const updateStoreInfo = (info: StoreInfo) => {
            Object.assign(storeInfo, info);
        };

        return {
            storeInfo,
            updateStoreInfo,
        };
    },

    {
        persist: {
            key: "storeInfo",
            storage: sessionStorage,
        },
    },
);
